<?php

return array(
	'key' => 'group_blog',
	'title' => 'Blog',
	'fields' => array(
		array(
			'key' => 'field_5cd07fddb9ab4',
			'label' => 'Posts Source',
			'name' => 'blog_posts_source',
			'type' => 'button_group',
			'instructions' => 'Choose where the posts get pulled from, Choosing Wordpress will run a normal Wordpress Posts Query with your chosen options. Choosing Post Picker will give you an option to manually choose which posts to show.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'wp_query' => 'Wordpress',
				'post_picker' => 'Post Picker',
			),
			'allow_null' => 0,
			'default_value' => 'wp_query',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5cd095e8b9ab7',
			'label' => 'Ignore Sticky Posts',
			'name' => 'blog_ignore_sticky_posts',
			'type' => 'true_false',
			'instructions' => 'Ignore Sticky Posts stops wordpress from pushing stickied posts to the top of the results. NOTE: Has no effect if using category or tag filtering.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => 'Ignore Sticky Posts',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5cd096d7b9ab8',
			'label' => 'Posts Per Page',
			'name' => 'blog_posts_per_page',
			'type' => 'number',
			'instructions' => 'Optional. The number of posts to show. If left blank, it defaults to Wordpress settings.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd07fddb9ab4',
						'operator' => '==',
						'value' => 'wp_query',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Posts Per Page (Optional)',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => 1,
		),
		array(
			'key' => 'field_5cc0d90071ce4',
			'label' => 'Post Picker',
			'name' => 'blog_post_picker',
			'type' => 'relationship',
			'instructions' => 'Manually select a collection of blog posts from the available items.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd07fddb9ab4',
						'operator' => '==',
						'value' => 'post_picker',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'post',
			),
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => array(
				0 => 'featured_image',
			),
			'min' => '',
			'max' => '',
			'return_format' => 'id',
		),
		array(
			'key' => 'field_5cd0a9022ded6',
			'label' => 'Cards',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd09bb75cf8d',
						'operator' => '==',
						'value' => 'cards',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd09770b9ab9',
			'label' => 'Show Featured Image',
			'name' => 'blog_show_featured_image',
			'type' => 'true_false',
			'instructions' => 'Whether to show the Posts Featured Image in the results.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show Featured Image',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5cd0a95a2ded8',
			'label' => 'Card Image Position',
			'name' => 'blog_cards_image_position',
			'type' => 'radio',
			'instructions' => 'Choose the position of the featured image on the card. Top shows the image at the top of the card. Background makes the featured image a background of the card. Option has no effect if Show Featured Image is turned off.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd09770b9ab9',
						'operator' => '==',
						'value' => 1,
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'top' => 'Top',
				'cover' => 'Background',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'top',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5cd103c4e2cf6',
			'label' => 'Carousel',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd09bb75cf8d',
						'operator' => '==',
						'value' => 'cards',
					),
					array(
						'field' => 'field_5cd0a8252ded5',
						'operator' => '==',
						'value' => 'carousel',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_89hrueis3ewanour9',
			'label' => 'Show Pagination Dots`',
			'name' => 'blog_carousel_pagination',
			'type' => 'true_false',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_4w35yeturtewwae',
			'label' => 'Show Navigation Arrows',
			'name' => 'blog_carousel_navigation',
			'type' => 'true_false',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5cd10ec2e2cff',
			'label' => 'Autoplay',
			'name' => 'blog_carousel_autoplay',
			'type' => 'true_false',
			'instructions' => 'Allow the carousel to automatically change slides.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '51',
				'class' => '',
				'id' => '',
			),
			'message' => 'Autoplay',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5cd1a9249e83b',
			'label' => 'Autoplay Delay',
			'name' => 'blog_carousel_autoplay_delay',
			'type' => 'number',
			'instructions' => 'Delay (ms) between slides auto changing.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd10ec2e2cff',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'default_value' => 3000,
			'placeholder' => 3000,
			'prepend' => '',
			'append' => 'milliseconds',
			'min' => '',
			'max' => '',
			'step' => 50,
		),
		array(
			'key' => 'field_5cd10ea5e2cfe',
			'label' => 'Loop',
			'name' => 'blog_carousel_loop',
			'type' => 'true_false',
			'instructions' => 'Allow the carousel to loop back to the beginning.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '51',
				'class' => '',
				'id' => '',
			),
			'message' => 'Loop',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5cd10eede2d00',
			'label' => 'Speed',
			'name' => 'blog_carousel_speed',
			'type' => 'number',
			'instructions' => 'Speed at which the carousel slides.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'default_value' => 300,
			'placeholder' => 300,
			'prepend' => '',
			'append' => 'milliseconds',
			'min' => '',
			'max' => '',
			'step' => 50,
		),
		array(
			'key' => 'field_5450vn348sj32',
			'label' => 'Lazy Load Images',
			'name' => 'blog_carousel_lazy_load',
			'type' => 'true_false',
			'instructions' => 'Lazy Load the Blog Images',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Lazy Load',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5cd0a5a847a83',
			'label' => 'Filtering',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd07fddb9ab4',
						'operator' => '==',
						'value' => 'wp_query',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd093d6b9ab5',
			'label' => 'Category',
			'name' => 'blog_category',
			'type' => 'taxonomy',
			'instructions' => 'Choose categories to filter the results by.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '51',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'checkbox',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
		),
		array(
			'key' => 'field_5cd0c4dcac118',
			'label' => 'Category Logical Relationship',
			'name' => 'blog_filter_category_relationship',
			'type' => 'button_group',
			'instructions' => 'Choose the comparison between Categories. ALL (AND) returns posts that satisfy all filters chosen. ANY (OR) returns posts that satisfy any filter chosen.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd093d6b9ab5',
						'operator' => '!=empty',
					),
				),
			),
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'IN' => 'ANY',
				'AND' => 'ALL',
			),
			'allow_null' => 0,
			'default_value' => 'IN',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5cc0d8b171ce3',
			'label' => 'Tag',
			'name' => 'blog_tag',
			'type' => 'taxonomy',
			'instructions' => 'Choose tags to filter the results by.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '51',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'post_tag',
			'field_type' => 'checkbox',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
			'allow_null' => 0,
		),
		array(
			'key' => 'field_5cd0c4f5276bc',
			'label' => 'Tag Logical Relationship',
			'name' => 'blog_filter_tag_relationship',
			'type' => 'button_group',
			'instructions' => 'Choose the comparison between Tags. ALL returns posts that satisfy all filters chosen. ANY returns posts that satisfy any filter chosen.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cc0d8b171ce3',
						'operator' => '!=empty',
					),
				),
			),
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'IN' => 'ANY',
				'AND' => 'ALL',
			),
			'allow_null' => 0,
			'default_value' => 'IN',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5cd094e1b9ab6',
			'label' => 'Taxonomy Logical Relationship',
			'name' => 'blog_filter_taxonomy_relationship',
			'type' => 'button_group',
			'instructions' => 'Choose the logical comparison between Categories & Tags. ANY (OR) returns all posts that satisfy any filter chosen. ALL (AND) returns only posts that satisfy all filters chosen.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd093d6b9ab5',
						'operator' => '!=empty',
					),
					array(
						'field' => 'field_5cc0d8b171ce3',
						'operator' => '!=empty',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'OR' => 'ANY',
				'AND' => 'ALL',
			),
			'allow_null' => 0,
			'default_value' => 'OR',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5cd0a08df5c75',
			'label' => 'Sorting',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd07fddb9ab4',
						'operator' => '==',
						'value' => 'wp_query',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd0994ab9abc',
			'label' => 'Order',
			'name' => 'blog_sort_order',
			'type' => 'radio',
			'instructions' => 'ASC - order from lowest to highest.
DESC - order from highest to lowest.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'ASC' => 'ASC',
				'DESC' => 'DESC',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'DESC',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5cd099a3b9abd',
			'label' => 'Order By',
			'name' => 'blog_sort_orderby',
			'type' => 'select',
			'instructions' => 'The post data to sort by.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'title' => 'Title',
				'date' => 'Date',
				'rand' => 'Random',
			),
			'default_value' => array(
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
	),
	'design_tab' => array(
		// array(
		// 	'key' => 'field_5cd0b2782c507',
		// 	'label' => 'Layout',
		// 	'name' => '',
		// 	'type' => 'tab',
		// 	'instructions' => '',
		// 	'required' => 0,
		// 	'conditional_logic' => 0,
		// 	'wrapper' => array(
		// 		'width' => '',
		// 		'class' => '',
		// 		'id' => '',
		// 	),
		// 	'placement' => 'top',
		// 	'endpoint' => 0,
		// ),
		array(
			'key' => 'field_5cd09bb75cf8d',
			'label' => 'Layout Type',
			'name' => 'blog_layout',
			'type' => 'button_group',
			'instructions' => 'Choose the type of layout for the blog posts. Feed is the Default Blog home layout. Card Grid is a grid of card posts. Card Carousel is a carousel of card posts.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'feed' => 'Blog Feed',
				'cards' => 'Blog Cards',
			),
			'allow_null' => 0,
			'default_value' => 'feed',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5cd0a8252ded5',
			'label' => 'Cards Layout',
			'name' => 'blog_layout_cards',
			'type' => 'radio',
			'instructions' => 'Choose the type of Blog Card layout.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd09bb75cf8d',
						'operator' => '==',
						'value' => 'cards',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'grid' => 'Grid',
				'carousel' => 'Carousel',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'grid',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_97834jk3xm039ads',
			'label' => 'Layout',
			'name' => 'blog_cards_carousel_layout',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd0a8252ded5',
						'operator' => '==',
						'value' => 'carousel',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'title-top' => 'Title Top',
				'title-left' => 'Title Left',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5cd10e2de2cf9',
			'label' => 'Cards Per View - Small',
			'name' => 'blog_cards_per_view_sm',
			'type' => 'number',
			'instructions' => 'Number of cards to show on small screens (mobile phones)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd09bb75cf8d',
						'operator' => '==',
						'value' => 'cards',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Cards Per View',
			'prepend' => '',
			'append' => 'card(s)',
			'min' => 1,
			'max' => 5,
			'step' => 0.1,
		),
		array(
			'key' => 'field_5cd10e6de2cfc',
			'label' => 'Cards Per View - Medium',
			'name' => 'blog_cards_per_view_md',
			'type' => 'number',
			'instructions' => 'Number of cards to show on medium screens (tablet)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd09bb75cf8d',
						'operator' => '==',
						'value' => 'cards',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Cards Per View',
			'prepend' => '',
			'append' => 'card(s)',
			'min' => 1,
			'max' => 5,
			'step' => 0.1,
		),
		array(
			'key' => 'field_5cd10e80e2cfd',
			'label' => 'Cards Per View - Large',
			'name' => 'blog_cards_per_view_lg',
			'type' => 'number',
			'instructions' => 'Number of cards to show on large screens (desktop)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd09bb75cf8d',
						'operator' => '==',
						'value' => 'cards',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Cards Per View',
			'prepend' => '',
			'append' => 'card(s)',
			'min' => 1,
			'max' => 5,
			'step' => 0.1,
		),
		array(
			'key' => 'field_5cd1db42fad9d',
			'label' => 'Cards Per View - XLarge',
			'name' => 'blog_cards_per_view_xl',
			'type' => 'number',
			'instructions' => 'Number of cards to show on Xlarge screens (desktop xl)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5cd09bb75cf8d',
						'operator' => '==',
						'value' => 'cards',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Cards Per View',
			'prepend' => '',
			'append' => 'card(s)',
			'min' => 1,
			'max' => 5,
			'step' => 0.1,
		),
	),
);
