<?php

return array(
	'key' => 'group_text_media',
	'title' => 'Text Media',
	'fields' => array(
		array(
			'key' => 'field_5c2e6759afd99',
			'label' => 'Button',
			'name' => 'text_media_button',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_5c2e677cafd9a',
			'label' => 'Media Type',
			'name' => 'text_media_media_type',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '51',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'image' => 'Image',
				'video' => 'Video',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5c2e6803afd9b',
			'label' => 'Image',
			'name' => 'text_media_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e677cafd9a',
						'operator' => '==',
						'value' => 'image',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5c38c62a280d9',
			'label' => 'Video Type',
			'name' => 'text_media_video_type',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e677cafd9a',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'file' => 'File',
				'link' => 'Link',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5c2e6828afd9c',
			'label' => 'Video',
			'name' => 'text_media_video',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e677cafd9a',
						'operator' => '==',
						'value' => 'video',
					),
					array(
						'field' => 'field_5c38c62a280d9',
						'operator' => '==',
						'value' => 'file',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '.mp4, .webm',
		),
		array(
			'key' => 'field_6054e30048858',
			'label' => 'Video Embed',
			'name' => 'text_media_video_embed',
			'type' => 'oembed',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e677cafd9a',
						'operator' => '==',
						'value' => 'video',
					),
					array(
						'field' => 'field_5c38c62a280d9',
						'operator' => '==',
						'value' => 'link',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'width' => '',
			'height' => '',
		),
		array(
			'key' => 'field_5c2e686eafd9d',
			'label' => 'Video Poster',
			'name' => 'text_media_video_poster',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e677cafd9a',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'design_tab' => array(
		array(
			'key' => 'field_5c2e68e8afd9f',
			'label' => 'Media Position',
			'name' => 'text_media_media_position',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'top' => 'Top',
				'right' => 'Right',
				'bottom' => 'Bottom',
				'left' => 'Left',
			),
			'default_value' => 'left',
			'allow_null' => 0,
			'default_value' => 'half',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_6054d5a316a81',
			'label' => 'Media Width',
			'name' => 'text_media_media_width',
			'type' => 'range',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e68e8afd9f',
						'operator' => '==',
						'value' => 'left',
					),
				),
				array(
					array(
						'field' => 'field_5c2e68e8afd9f',
						'operator' => '==',
						'value' => 'right',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 6,
			'min' => 4,
			'max' => 8,
			'step' => '',
			'prepend' => 'col-md-',
			'append' => '',
		),
		array(
			'key' => 'field_6054e10e0d6f4',
			'label' => 'Video Playback Style',
			'name' => 'text_media_video_playback_style',
			'type' => 'button_group',
			'instructions' => 'Choose a video playback style. <br><strong>Popup</strong> will display the video poster and a play button to allow you to play the video in an overlay. <br><strong>Background</strong> Will just play the video on load inline. If using "Link" video type, style will always use to "popup" regardless of setting.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e677cafd9a',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'popup' => 'Popup',
				'background' => 'Background',
			),
			'allow_null' => 0,
			'default_value' => 'popup',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_51xdfjh405m39',
			'label' => 'Background Properties',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e677cafd9a',
						'operator' => '==',
						'value' => 'image',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Configure your background image properties below',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_52xdjd03hhcbs',
			'label' => 'Background Position',
			'name' => 'text_media_image_position',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e677cafd9a',
						'operator' => '==',
						'value' => 'image',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'top left' => 'Top Left',
				'top center' => 'Top Center',
				'top right' => 'Top Right',
				'center left' => 'Center Left',
				'center center' => 'Center Center',
				'center right' => 'Center Right',
				'bottom left' => 'Bottom Left',
				'bottom center' => 'Bottom Center',
				'bottom right' => 'Bottom Right',
			),
			'default_value' => array(
				0 => 'center center',
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_54xagg2383jd2',
			'label' => 'Background Size',
			'name' => 'text_media_image_size',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e677cafd9a',
						'operator' => '==',
						'value' => 'image',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'auto' => 'Auto',
				'cover' => 'Cover',
				'contain' => 'Contain',
				'custom' => 'Custom',
			),
			'default_value' => array(
				0 => 'cover',
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_55x984hd93df2',
			'label' => 'Background Custom Size',
			'name' => 'text_media_image_custom_size',
			'type' => 'text',
			'instructions' => 'Enter a Custom Image Size Value',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c2e677cafd9a',
						'operator' => '==',
						'value' => 'image',
					),
					array(
						'field' => 'field_54xagg2383jd2',
						'operator' => '==',
						'value' => 'custom',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '100% 100%',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
);