<?php

return array(
	'key' => 'group_image_gallery',
	'title' => 'Image Gallery',
	'fields' => array(
		array(
			'key' => 'field_45c09m34830bbt37',
			'label' => 'Heading Layout Columns',
			'name' => 'heading_layout_columns',
			'type' => 'true_false',
			'instructions' => 'Choose the Heading Layout.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '51',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show Heading as 2 columns',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_84765jhgxjhf2e6596n',
			'label' => 'Heading Alignment',
			'name' => 'heading_alignment',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_45c09m34830bbt37',
						'operator' => '!=',
						'value' => 1,
					),
				),
			),
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'left' => 'Left',
				'center' => 'Center',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5c353625f3c07',
			'label' => 'Image Gallery',
			'name' => 'image_gallery',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'insert' => 'append',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '.jpg, .jpeg, .png, .gif',
		),
		array(
			'key' => 'field_30984nkjh3nm2x384n7',
			'label' => 'Carousel',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_60661c7d21ea9',
						'operator' => '==',
						'value' => 'carousel',
					),
				),
				array(
					array(
						'field' => 'field_60661c7d21ea9',
						'operator' => '==',
						'value' => 'slider',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_29837fnhgkbx3d4',
			'label' => 'Show Navigation Arrows',
			'name' => 'image_gallery_carousel_show_navigation',
			'type' => 'true_false',
			'instructions' => 'Whether to show the navigation arrows on the carousel',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25.5',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show Arrows',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_606b452ay35df',
			'label' => 'Navigation Position',
			'name' => 'navigation_position',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_29837fnhgkbx3d4',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'left' => 'Left',
				'sides' => 'Sides',
				'right' => 'Right',
			),
			'allow_null' => 0,
			'default_value' => 'sides',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_9384jhkg276f5',
			'label' => 'Show Pagination Dots',
			'name' => 'image_gallery_carousel_show_pagination',
			'type' => 'true_false',
			'instructions' => 'Whether to show the pagination dots on the carousel',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25.5',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show Dots',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_3985djkfkjhg266h',
			'label' => 'Swiper Controls Layout',
			'name' => 'image_gallery_swiper_controls_layout',
			'type' => 'button_group',
			'instructions' => 'Choose the Layout of the swiper controls',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_60661c7d21ea9',
						'operator' => '==',
						'value' => 'carousel',
					),
				),
			),
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'pagination-navigation' => 'Pagination <-> Navigation',
				'navigation-pagination' => 'Navigation <-> Pagination',
			),
			'allow_null' => 0,
			'default_value' => 'pagination-navigation',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
	),
	'design_tab' => array(
		array(
			'key' => 'field_60661c7d21ea9',
			'label' => 'Image Gallery Layout',
			'name' => 'image_gallery_layout',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'grid' => 'Grid',
				'masonry' => 'Masonry',
				'slider' => 'Slider',
				'carousel' => 'Carousel',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5c36261e64132',
			'label' => 'Gallery Columns',
			'name' => 'image_gallery_columns',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_60661c7d21ea9',
						'operator' => '==',
						'value' => 'grid',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				1 => '1',
				2 => '2',
				3 => '3',
				4 => '4',
				5 => '5',
				6 => '6',
				8 => '8',
			),
			'default_value' => array(
				0 => 3,
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
	)
);
