<?php
declare( strict_types = 1 );
namespace App\Setup;

class Options
{
	/**
	 * Initialization
	 * This method should be run from functions.php
	 */
	public static function init()
	{
		add_action( 'acf/init',   [__CLASS__, 'add_options_page'] );
		add_action( 'acf/init',   [__CLASS__, 'theme_options_page_fields'] );
	}

	/**
	 * Requires ACF Theme Options Page Fields
	 */
	public static function theme_options_page_fields()
	{
		if( function_exists('acf_add_local_field_group') ):
			acf_add_local_field_group(array(
				'key' => 'group_5ba1c04eb6142',
				'title' => 'Theme Options',
				'fields' => array(
					array(
						'key' => 'field_5ba1c7377bafc',
						'label' => 'Header',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_4859wetrhusigfd',
						'label' => 'Preheader Options',
						'name' => '',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'new_lines' => 'wpautop',
						'esc_html' => 0,
					),
					array(
						'key' => 'field_6037e91e58a37',
						'label' => 'Use Preheader',
						'name' => 'use_preheader',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '51',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_6037f3aabc857',
						'label' => 'Preheader Mobile',
						'name' => 'preheader_mobile',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_6037e91e58a37',
									'operator' => '==',
									'value' => '1',
								),
							),
						),
						'wrapper' => array(
							'width' => '49',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'contact' => 'Contact',
							'menu' => 'Menu',
							'search' => 'Search',
						),
						'default_value' => array(
							0 => 'menu',
						),
						'allow_null' => 1,
						'multiple' => 1,
						'ui' => 1,
						'ajax' => 1,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array(
						'key' => 'field_44wtersyhdfjy',
						'label' => 'Header Link Options',
						'name' => '',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'new_lines' => 'wpautop',
						'esc_html' => 0,
					),
					array(
						'key' => 'field_453tyrtjfhgdf',
						'label' => 'Header Link',
						'name' => 'header_link',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '51',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
					array(
						'key' => 'field_q8eurhfbjdsksqwi',
						'label' => 'Header Link Location',
						'name' => 'header_link_location',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_453tyrtjfhgdf',
									'operator' => '!=empty',
								),
							),
						),
						'wrapper' => array(
							'width' => '49',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'preheader' => 'Preheader',
							'header' => 'Header',
						),
						'allow_null' => 0,
						'default_value' => 'null',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_42wrstegdfsdf',
						'label' => 'Header Login Link',
						'name' => 'header_login_link',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '51',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
					array(
						'key' => 'field_etrgdfxsae',
						'label' => 'Login Location',
						'name' => 'login_location',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '49',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'preheader' => 'Preheader',
							'header' => 'Header',
							'none' => 'None'
						),
						'allow_null' => 0,
						'default_value' => 'null',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_q39v8uha3v4aw4',
						'label' => 'Header Design',
						'name' => '',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'new_lines' => 'wpautop',
						'esc_html' => 0,
					),
					array(
						'key' => 'field_5ba1c97ded508',
						'label' => 'Header Positioning Type',
						'name' => 'header_positioning_type',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'fixed' => 'Fixed',
							'static' => 'Static',
						),
						'allow_null' => 0,
						'default_value' => 'fixed',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),

					array(
						'key' => 'field_603803ad246bc',
						'label' => 'Header Container',
						'name' => 'header_container',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'container' => 'Contained',
							'container-fluid' => 'Fluid',
						),
						'allow_null' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_60380405246bd',
						'label' => 'Logo Location',
						'name' => 'logo_location',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left' => 'Left',
							'center' => 'Center',
						),
						'allow_null' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_60380439246bf',
						'label' => 'Menu Text Align',
						'name' => 'menu_text_align',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left' => 'Left',
							'center' => 'Center',
							'right' => 'Right',
						),
						'allow_null' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_60380450246c0',
						'label' => 'Hamburger Align',
						'name' => 'hamburger_align',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left' => 'Left',
							'right' => 'Right',
							'far-right' => 'Far Right',
						),
						'allow_null' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_60380466246c1',
						'label' => 'Button Design',
						'name' => 'button_design',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'primary' => 'Primary',
							'full' => 'Full',
						),
						'allow_null' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_6038049b246c2',
						'label' => 'Dropdown Style',
						'name' => 'dropdown_style',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'default' => 'Default',
							'icon' => 'Icon',
						),
						'allow_null' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_34253w6ryuhdgsfe',
						'label' => 'Mobile Options',
						'name' => '',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'new_lines' => 'wpautop',
						'esc_html' => 0,
					),
					array(
						'key' => 'field_603804cc246c3',
						'label' => 'Mobile Logo Location',
						'name' => 'mobile_logo_location',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left' => 'Left',
							'center' => 'Center',
						),
						'allow_null' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_603804ff246c5',
						'label' => 'Mobile Menu Location',
						'name' => 'mobile_menu_location',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left' => 'Left',
							'right' => 'Right',
						),
						'allow_null' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_60380521246c6',
						'label' => 'Mobile Flyout Align',
						'name' => 'mobile_flyout_align',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left' => 'Left',
							'center' => 'Center',
							'right' => 'Right',
						),
						'allow_null' => 0,
						'default_value' => 'left',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_453westydr543re',
						'label' => 'Search Options',
						'name' => '',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'new_lines' => 'wpautop',
						'esc_html' => 0,
					),
					array(
						'key' => 'field_536eryuftjgkvg',
						'label' => 'Search Location',
						'name' => 'search_location',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '51',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'preheader' => 'Preheader',
							'header' => 'Header',
							'none' => 'None',
						),
						'allow_null' => 0,
						'default_value' => 'header',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_345weytrjrsdg',
						'label' => 'Search Design',
						'name' => 'search_design',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_536eryuftjgkvg',
									'operator' => '==',
									'value' => 'header',
								),
							),
						),
						'wrapper' => array(
							'width' => '49',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'full' => 'Full',
							'short' => 'Short',
						),
						'allow_null' => 0,
						'default_value' => 'full',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_5p39hdkdncwp3',
						'label' => 'Tracking/Analytics',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5ba1c7757bafd',
						'label' => 'Google Analytics',
						'name' => 'google_analytics',
						'type' => 'textarea',
						'instructions' => 'Enter the Google Analytics Tracking Code',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 11,
						'new_lines' => '',
					),
					array(
						'key' => 'field_53m934mvu3430',
						'label' => 'Facebook Pixel',
						'name' => 'facebook_pixel',
						'type' => 'textarea',
						'instructions' => 'Enter the Facebook Pixel Tracking Code',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 17,
						'new_lines' => '',
					),
					array(
						'key' => 'field_59sjo3x3o34s2',
						'label' => 'Bing Pixel',
						'name' => 'bing_pixel',
						'type' => 'textarea',
						'instructions' => 'Enter the Bing Pixel Tracking Code',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
					),
					array(
						'key' => 'field_5ba26139f7892',
						'label' => 'API Keys',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5ba1c968ed507',
						'label' => 'Google Maps API Key',
						'name' => 'google_maps_api_key',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba26149f7893',
						'label' => 'Twitter API Key',
						'name' => 'twitter_api_key',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba26152f7894',
						'label' => 'Instagram API Key',
						'name' => 'instagram_api_key',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba1c86344d49',
						'label' => 'Social Media',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5ba1c7ffc2ba7',
						'label' => 'Facebook Link',
						'name' => 'facebook_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5ba1c813c2ba8',
						'label' => 'Twitter Link',
						'name' => 'twitter_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5ba1c81dc2ba9',
						'label' => 'Instagram Link',
						'name' => 'instagram_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5ba1c825c2baa',
						'label' => 'Youtube Link',
						'name' => 'youtube_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5mm3a4v4m88mx',
						'label' => 'Pinterest Link',
						'name' => 'pinterest_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5ba1cajs84ns0',
						'label' => 'Linkedin',
						'name' => 'linkedin_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5skdjfh385e62',
						'label' => 'Flickr',
						'name' => 'flickr_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5ba1ca3a35e62',
						'label' => 'Google Plus',
						'name' => 'google_plus_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5ba1cb22eba88',
						'label' => 'Contact Info',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5ba1cb45eba89',
						'label' => 'Address',
						'name' => 'address',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 3,
						'new_lines' => 'br',
					),
					array(
						'key' => 'field_5ba1cb74eba8a',
						'label' => 'Phone Number',
						'name' => 'phone_number',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '(555) 555-5555',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba26166f7895',
						'label' => 'Email',
						'name' => 'email',
						'type' => 'email',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_5ba1dkfj2s83d',
						'label' => 'Google Maps URL',
						'name' => 'google_maps_url',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'https://www.google.com/maps/place/XXX/@xx.x,xxx.x',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba1987df330',
						'label' => 'Google Map Embed Code',
						'name' => 'google_map_embed_code',
						'type' => 'textarea',
						'instructions' => 'No API Key Required',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '<iframe src="https://www.google.com/maps/embed?xxx"></iframe>',
						'maxlength' => '',
						'rows' => 3,
						'new_lines' => '',
					),
					array(
						'key' => 'field_5bdc7d1763165',
						'label' => 'Google Map',
						'name' => 'google_map',
						'type' => 'google_map',
						'instructions' => 'API Key Required',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'center_lat' => '',
						'center_lng' => '',
						'zoom' => '',
						'height' => '',
					),
					array(
						'key' => 'field_5ba1c7cac2ba5',
						'label' => 'Footer',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5ba1caa3eba87',
						'label' => 'Bottom Bar',
						'name' => 'footer_bottom_bar',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
					),
					array(
						'key' => 'field_6035a1252efbd',
						'label' => 'Footer Text Align',
						'name' => 'footer_legal_text_align',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left' => 'Left',
							'center' => 'Center',
							'right' => 'Right',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6035a2e37daf8',
						'label' => 'Footer Social Media Order',
						'name' => 'footer_legal_social_media_order',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'first' => 'Left',
							'last' => 'Right',
							'none' => 'None',
						),
						'allow_null' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_425wrtesdghfc',
						'label' => 'Footer Media Position',
						'name' => 'footer_social_media_position',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'left' => 'Left',
							'right' => 'Right',
							'none' => 'None',
						),
						'allow_null' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_6036bfa920194',
						'label' => 'Use Wide Widget',
						'name' => 'use_wide_widget',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_5bd77877c8550',
						'label' => 'Login Page',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5bd78770fcf3c',
						'label' => 'Login Logo',
						'name' => 'login_logo',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '.jpg, .png',
					),
					array(
						'key' => 'field_5bd7788ac8551',
						'label' => 'Login BG Type',
						'name' => 'login_bg_type',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'color' => 'Color',
							'image' => 'Image',
						),
						'allow_null' => 1,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
					array(
						'key' => 'field_5bd778cfc8552',
						'label' => 'Login BG Color',
						'name' => 'login_bg_color',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5bd7788ac8551',
									'operator' => '==',
									'value' => 'color',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
					),
					array(
						'key' => 'field_5bd778f0c8553',
						'label' => 'Login BG Image',
						'name' => 'login_bg_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5bd7788ac8551',
									'operator' => '==',
									'value' => 'image',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '.jpg, .png, .gif',
					),
					array(
						'key' => 'field_53xn4839049n2',
						'label' => 'Custom Scripts',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_5ba1c8d8ed505',
						'label' => 'Head Tag Scripts',
						'name' => 'global_head_scripts',
						'type' => 'textarea',
						'instructions' => 'Enter Scripts to be loaded in the head tag.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
					),
					array(
						'key' => 'field_43tyeshdfgswe45',
						'label' => 'Body Open Scripts',
						'name' => 'global_body_open_scripts',
						'type' => 'textarea',
						'instructions' => 'Enter Scripts to be loaded immediately after the body tag.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 11,
						'new_lines' => '',
					),
					array(
						'key' => 'field_5ba1c8f7ed506',
						'label' => 'Footer Scripts',
						'name' => 'global_footer_scripts',
						'type' => 'textarea',
						'instructions' => 'Enter Scripts to be loaded in the footer.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
					),
					array(
						'key' => 'field_604a5346303a4',
						'label' => 'Blog Posts',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_604a5350303a5',
						'label' => 'Blog Single Template',
						'name' => 'blog_single_template',
						'type' => 'select',
						'instructions' => 'Choose the Default Single Post Template',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'one' => 'Template One',
							'two' => 'Template Two',
							'three' => 'Template Three',
						),
						'default_value' => 'one',
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_604aa3b38c6df',
						'label' => 'Social Share Platforms',
						'name' => 'blog_social_share_platforms',
						'type' => 'checkbox',
						'instructions' => 'Choose which social platforms you wish to be able to share posts too',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'facebook' => 'Facebook',
							'twitter' => 'Twitter',
							'linkedin' => 'Linkedin',
						),
						'allow_custom' => 0,
						'default_value' => array(
							0 => 'facebook',
							1 => 'twitter',
							2 => 'linkedin',
						),
						'layout' => 'vertical',
						'toggle' => 0,
						'return_format' => 'value',
						'save_custom' => 0,
					),
					array(
						'key' => 'field_604aa4088c6e0',
						'label' => 'Show Author',
						'name' => 'blog_show_author',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui' => 1,
						'ui_on_text' => 'Show',
						'ui_off_text' => 'Hide',
					),
					array(
						'key' => 'field_604aa4248c6e1',
						'label' => 'Show Date',
						'name' => 'blog_show_date',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui' => 1,
						'ui_on_text' => 'Show',
						'ui_off_text' => 'Hide',
					),
					array(
						'key' => 'field_43w6tgfzaswerw',
						'label' => 'Related Posts Heading',
						'name' => 'related_posts_heading',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array(
						'key' => 'field_603e862060183',
						'label' => '404',
						'name' => '',
						'type' => 'tab',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placement' => 'left',
						'endpoint' => 0,
					),
					array(
						'key' => 'field_603e84ee6017d',
						'label' => 'Heading',
						'name' => '404_header',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '4',
						'new_lines' => 'br',
					),
					array(
						'key' => 'field_603e85216017f',
						'label' => 'Heading Tag',
						'name' => '404_header_tag',
						'type' => 'select',
						'instructions' => 'Choose a Heading Tag',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.33',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'h1' => 'H1',
							'h2' => 'H2',
							'h3' => 'H3',
							'h4' => 'H4',
							'h5' => 'H5',
							'h6' => 'H6',
							'p' => 'P',
						),
						'default_value' => false,
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_603e84f96017e',
						'label' => 'Heading Style',
						'name' => '404_header_style',
						'type' => 'select',
						'instructions' => 'Choose the Heading Style',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.33',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'h1' => 'H1',
							'h2' => 'H2',
							'h3' => 'H3',
							'h4' => 'H4',
							'h5' => 'H5',
							'h6' => 'H6',
							'display-1' => 'Display 1',
							'display-2' => 'Display 2',
							'display-3' => 'Display 3',
							'display-4' => 'Display 4',
							'lead' => 'Lead',
						),
						'default_value' => false,
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_603e856960180',
						'label' => 'Heading Custom Class',
						'name' => '404_header_custom_class',
						'type' => 'text',
						'instructions' => 'Add Custom Class',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.33',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_603e85e660181',
						'label' => 'Subheading',
						'name' => '404_subheading',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_603e85fd60182',
						'label' => 'Link',
						'name' => '404_link',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
					array(
						'key' => 'field_603e81696017c',
						'label' => 'Background Image',
						'name' => '404_background_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'medium_large',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '.jpg, .png, .jpeg, .gif',
					),
					array(
						'key' => 'field_603e870339650',
						'label' => 'Text Theme',
						'name' => '404_text_theme',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'dark' => 'Dark',
							'light' => 'Light',
						),
						'allow_null' => 0,
						'default_value' => 'dark',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'options_page',
							'operator' => '==',
							'value' => 'theme-options',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => 1,
				'description' => '',
			));

			acf_add_local_field_group(array(
				'key' => 'group_5e4adgadga6eca5f',
				'title' => 'Page Custom Scripts',
				'fields' => array(
					array(
						'key' => 'field_43tyeaddgadgagfgswe45',
						'label' => 'Head Tag Scripts',
						'name' => 'page_head_scripts',
						'type' => 'textarea',
						'instructions' => 'Enter Tag Scripts to be loaded in the head',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 6,
						'new_lines' => '',
					),
					array(
						'key' => 'field_4nm0923049c35m049504',
						'label' => 'Body Open Scripts',
						'name' => 'page_body_open_scripts',
						'type' => 'textarea',
						'instructions' => 'Enter Scripts to be loaded immediately after the body tag.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 6,
						'new_lines' => '',
					),
				),
				'location' => array(
					array(
						array(
							'param' => 'post_type',
							'operator' => '!=',
							'value' => 'global-components',
						),
					),
				),
				'menu_order' => 50,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => true,
				'description' => '',
			));
		endif;
	}

	/**
	 * ACF Options Page
	 */
	public static function add_options_page()
	{
		if( function_exists('acf_add_options_page') ) {

			acf_add_options_page(array(
				'page_title'    => 'Theme Options',
				'menu_title'    => 'Theme Options',
				'menu_slug'     => 'theme-options',
				'icon_url'      => 'dashicons-admin-settings',
				'capability'    => 'update_core',
				'position'      => 2
			));

		}
	}
}
