<?php
return array(
	'key' => 'group_video_player',
	'title' => 'Video Player',
	'fields' => array(
		array(
			'key' => 'field_3rghjiuy6tr',
			'label' => 'Video Player',
			'name' => 'video_player_items',
			'type' => 'repeater',
			'instructions' => 'Add Videos',
			'layout' => 'block',
			'button_label' => 'Add Video',
			'sub_fields' => array(
				array(
					'key' => 'field_983m4983bv5in9',
					'label' => 'Video Title',
					'name' => 'video_player_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_gbniu38nt0u522',
					'label' => 'Video Description',
					'name' => 'video_player_description',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '3',
					'new_lines' => 'br',
				),
				array(
					'key' => 'field_539483n4374nbb9',
					'label' => 'Poster',
					'name' => 'video_player_poster',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '.jpg, .png',
				),
				array(
					'key' => 'field_3o34um03948m0394',
					'label' => 'Video Player Sources',
					'name' => 'video_player_sources',
					'type' => 'repeater',
					'instructions' => 'Video items will be attempted to play in the order provided. Only the first video that the browser is capable of playing will actually play.',
					'layout' => 'block',
					'button_label' => 'Add Video Source',
					'sub_fields' => array(
						array(
							'key' => 'field_239487n30m34jd83',
							'label' => 'Video Source',
							'name' => 'video',
							'type' => 'file',
							'required' => 1,
							'return_format' => 'array',
							'library' => 'all',
							'mime_types' => '.mp4, .webm',
						),
					),
				),
			),
		),
		array(
			'key' => 'field_53498ydkj3bkjbe9',
			'label' => 'Carousel',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_609163207e3d0',
						'operator' => '==',
						'value' => 'carousel',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_398dbd2md3igcf',
			'label' => 'Show Navigation Arrows',
			'name' => 'video_player_carousel_show_navigation',
			'type' => 'true_false',
			'instructions' => 'Whether to show the navigation arrows on the carousel',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25.5',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show Arrows',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_53r3u92vjdo3yf3',
			'label' => 'Show Pagination Dots',
			'name' => 'video_player_carousel_show_pagination',
			'type' => 'true_false',
			'instructions' => 'Whether to show the pagination dots on the carousel',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25.5',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show Dots',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_dkjb29twhd93vbv',
			'label' => 'Swiper Controls Layout',
			'name' => 'video_player_swiper_controls_layout',
			'type' => 'button_group',
			'instructions' => 'Choose the Layout of the swiper controls',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'pagination-navigation' => 'Pagination <-> Navigation',
				'navigation-pagination' => 'Navigation <-> Pagination',
			),
			'allow_null' => 0,
			'default_value' => 'pagination-navigation',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5892gdbmcf956r',
			'label' => 'Autoplay',
			'name' => 'video_player_carousel_autoplay',
			'type' => 'true_false',
			'instructions' => 'Allow the carousel to automatically change slides.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '51',
				'class' => '',
				'id' => '',
			),
			'message' => 'Autoplay',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_f095uijdi38g3',
			'label' => 'Autoplay Delay',
			'name' => 'video_player_carousel_autoplay_delay',
			'type' => 'number',
			'instructions' => 'Delay (ms) between slides auto changing.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_59384kdf2xxs2',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'default_value' => 3000,
			'placeholder' => 3000,
			'prepend' => '',
			'append' => 'milliseconds',
			'min' => '',
			'max' => '',
			'step' => 100,
		),
		array(
			'key' => 'field_dfkjbd939tsi3c',
			'label' => 'Loop',
			'name' => 'video_player_carousel_loop',
			'type' => 'true_false',
			'instructions' => 'Allow the carousel to loop back to the beginning.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '51',
				'class' => '',
				'id' => '',
			),
			'message' => 'Loop',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_jkdgfkjdhhkjb432',
			'label' => 'Speed',
			'name' => 'video_player_carousel_speed',
			'type' => 'number',
			'instructions' => 'Speed at which the carousel slides',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 300,
			'prepend' => '',
			'append' => 'milliseconds',
			'min' => '',
			'max' => '',
			'step' => 50,
		),
		array(
			'key' => 'field_340938m4039403n',
			'label' => 'Lazy Load Images',
			'name' => 'video_player_carousel_lazy_load',
			'type' => 'true_false',
			'instructions' => 'Lazy Load the Cards Images',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '51',
				'class' => '',
				'id' => '',
			),
			'message' => 'Lazy Load',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_98762jhv87dg',
			'label' => 'Centered Slides',
			'name' => 'video_player_carousel_centered_slides',
			'type' => 'true_false',
			'instructions' => 'Center the Slides',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'message' => 'Center Slides',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'design_tab' => array (
		array(
			'key' => 'field_609163207e3d0',
			'label' => 'Layout',
			'name' => 'video_player_layout',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'single' => 'Single',
				'carousel' => 'Carousel',
			),
			'allow_null' => 0,
			'default_value' => 'single',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5340c3j534v9b5',
			'label' => 'Videos Per View - Small',
			'name' => 'video_player_cards_per_view_sm',
			'type' => 'number',
			'instructions' => 'Number of videos to show on small screens (mobile phones)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_609163207e3d0',
						'operator' => '==',
						'value' => 'carousel',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Videos Per View',
			'prepend' => '',
			'append' => 'card(s)',
			'min' => 1,
			'max' => 6,
			'step' => 0.1,
		),
		array(
			'key' => 'field_57fdjfgn0r984',
			'label' => 'Videos Per View - Medium',
			'name' => 'video_player_cards_per_view_md',
			'type' => 'number',
			'instructions' => 'Number of videos to show on medium screens (tablet)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_609163207e3d0',
						'operator' => '==',
						'value' => 'carousel',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Videos Per View',
			'prepend' => '',
			'append' => 'card(s)',
			'min' => 1,
			'max' => 6,
			'step' => 0.1,
		),
		array(
			'key' => 'field_by2t76r337hfk48',
			'label' => 'Videos Per View - Large',
			'name' => 'video_player_cards_per_view_lg',
			'type' => 'number',
			'instructions' => 'Number of videos to show on large screens (desktop)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_609163207e3d0',
						'operator' => '==',
						'value' => 'carousel',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Cards Per View',
			'prepend' => '',
			'append' => 'card(s)',
			'min' => 1,
			'max' => 6,
			'step' => 0.1,
		),
		array(
			'key' => 'field_3974ybwy3ojncf',
			'label' => 'Videos Per View - XLarge',
			'name' => 'video_player_cards_per_view_xl',
			'type' => 'number',
			'instructions' => 'Number of videos to show on Xlarge screens (desktop xl)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_609163207e3d0',
						'operator' => '==',
						'value' => 'carousel',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Videos Per View',
			'prepend' => '',
			'append' => 'card(s)',
			'min' => 1,
			'max' => 6,
			'step' => 0.1,
		),
	),
);
