<?php

return array(
	'key' => 'group_nlkgbnm78165',
	'title' => 'CTA',
	'fields' => array(
		array(
			'key' => 'field_b8k53c4m39x0385az',
			'label' => 'Button',
			'name' => 'cta_button',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_b8kb8k5kljhoiu6f01c3',
			'label' => 'Form',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_b8k5ppkjbh84b3b',
						'operator' => '==',
						'value' => 'form-right',
					),
				),
				array(
					array(
						'field' => 'field_b8k5ppkjbh84b3b',
						'operator' => '==',
						'value' => 'form-left',
					),
				),
				array(
					array(
						'field' => 'field_b8k5ppkjbh84b3b',
						'operator' => '==',
						'value' => 'form-stacked',
					),
				)
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_b8kb8k5alksdjngc6f8c5',
			'label' => 'Form',
			'name' => 'cta_form',
			'type' => 'forms',
			'instructions' => 'Choose a created Gravity Forms form in the list below.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'post_object',
			'allow_null' => 0,
			'multiple' => 0,
		),
		array(
			'key' => 'field_b8kb8k5bf07f5f644b3',
			'label' => 'Header Option',
			'name' => 'cta_form_header_option',
			'type' => 'button_group',
			'instructions' => 'Choose to use the Configured Gravity Forms Title & Description, A Custom Title & Description or No Title & Description. If Custom Header is chosen, the Header field above will be the form title.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'form' => 'Gravity Forms Header',
				'custom' => 'Custom Header',
				'none' => 'No Header',
			),
			'allow_null' => 0,
			'default_value' => 'form',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_b8kb8k6jhabe764f52',
			'label' => 'Custom Form Header',
			'name' => 'cta_form_custom_header',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_b8kb8k5bf07f5f644b3',
						'operator' => '==',
						'value' => 'custom',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_b8kb8k5bf08044644b6',
			'label' => 'Custom Description',
			'name' => 'cta_form_custom_description',
			'type' => 'wysiwyg',
			'instructions' => 'Enter a Custom Form Description',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_b8kb8k5bf07f5f644b3',
						'operator' => '==',
						'value' => 'custom',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_b8kb8k5bf084f6f01c3',
			'label' => 'Form Options',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_b8k5ppkjbh84b3b',
						'operator' => '==',
						'value' => 'form-right',
					),
				),
				array(
					array(
						'field' => 'field_b8k5ppkjbh84b3b',
						'operator' => '==',
						'value' => 'form-left',
					),
				),
				array(
					array(
						'field' => 'field_b8k5ppkjbh84b3b',
						'operator' => '==',
						'value' => 'form-stacked',
					),
				)
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_b8kb8k5bf090f19b6cb',
			'label' => 'Show Gravity Form Title',
			'name' => 'cta_form_show_gf_title',
			'type' => 'true_false',
			'instructions' => 'Whether or not to display the gravity form title. Note: has no effect if Custom Header or No Header options are chosen.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show Title',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_b8kb8k5bf091b89b6cc',
			'label' => 'Show Gravity Form Description',
			'name' => 'cta_form_show_gf_description',
			'type' => 'true_false',
			'instructions' => 'Whether or not to display the gravity form description. Note: has no effect if Custom Header or No Header options are chosen.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show Description',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_b8kb8k5bf080aa644b9',
			'label' => 'Ajax',
			'name' => 'cta_form_ajax',
			'type' => 'true_false',
			'instructions' => 'Whether or not to use AJAX for form submission.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'message' => 'Enable Ajax',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_b8kb8k5bf08253eabde',
			'label' => 'Tab Index',
			'name' => 'cta_form_tabindex',
			'type' => 'number',
			'instructions' => 'Specify the starting tab index for the fields of this form.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => 1,
			'placeholder' => 'Tab Index',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => 1,
		),
		array(
			'key' => 'field_b8kb8k5bf08094644b8',
			'label' => 'Display Inactive',
			'name' => 'cta_form_display_inactive',
			'type' => 'true_false',
			'instructions' => 'Whether or not to display the form even if it is inactive.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'message' => 'Display If Inactive',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'design_tab' => array(
		array(
			'key' => 'field_b8k5ppkjbh84b3b',
			'label' => 'CTA Template',
			'name' => 'cta_template',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'text' => 'Text',
				'split-text' => 'Split Text',
				'form-right' => 'Form Right',
				'form-left' => 'Form Left',
				'form-stacked' => 'Form Stacked',
			),
			'default_value' => array(
				0 => 'center center',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_b8k5bbbbb3584b3b',
			'label' => 'Text Positioning',
			'name' => 'cta_text_positioning',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'top left' => 'Top Left',
				'top center' => 'Top Center',
				'top right' => 'Top Right',
				'center left' => 'Center Left',
				'center center' => 'Center Center',
				'center right' => 'Center Right',
				'bottom left' => 'Bottom Left',
				'bottom center' => 'Bottom Center',
				'bottom right' => 'Bottom Right',
			),
			'default_value' => array(
				0 => 'center center',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
	),
);
