<?php

return array(
    'key' => 'group_form',
    'title' => 'Form',
    'fields' => array(
        array(
            'key' => 'field_5bf07f5f644b3',
            'label' => 'Header Option',
            'name' => 'form_header_option',
            'type' => 'button_group',
            'instructions' => 'Choose to use the Configured Gravity Forms Title & Description, A Custom Title & Description or No Title & Description. If Custom Header is chosen, the Header field above will be the form title.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'form' => 'Gravity Forms Header',
                'custom' => 'Custom Header',
                'none' => 'No Header',
            ),
            'allow_null' => 0,
            'default_value' => 'form',
            'layout' => 'horizontal',
            'return_format' => 'value',
        ),
        array(
            'key' => 'field_5bc65e8bdf8c5',
            'label' => 'Form',
            'name' => 'form',
            'type' => 'forms',
            'instructions' => 'Choose a created Gravity Forms form in the list below.',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'post_object',
            'allow_null' => 0,
            'multiple' => 0,
        ),
        array(
            'key' => 'field_5bf084f6f01c3',
            'label' => 'Form Options',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5bf090f19b6cb',
            'label' => 'Show Gravity Form Title',
            'name' => 'form_show_gf_title',
            'type' => 'true_false',
            'instructions' => 'Whether or not to display the gravity form title. Note: has no effect if Custom Header or No Header options are chosen.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'message' => 'Show Title',
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_5bf091b89b6cc',
            'label' => 'Show Gravity Form Description',
            'name' => 'form_show_gf_description',
            'type' => 'true_false',
            'instructions' => 'Whether or not to display the gravity form description. Note: has no effect if Custom Header or No Header options are chosen.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'message' => 'Show Description',
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_5bf080aa644b9',
            'label' => 'Ajax',
            'name' => 'form_ajax',
            'type' => 'true_false',
            'instructions' => 'Whether or not to use AJAX for form submission.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'message' => 'Enable Ajax',
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_5bf08253eabde',
            'label' => 'Tab Index',
            'name' => 'form_tabindex',
            'type' => 'number',
            'instructions' => 'Specify the starting tab index for the fields of this form.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'placeholder' => 'Tab Index',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => 1,
        ),
        array(
            'key' => 'field_5bf08094644b8',
            'label' => 'Display Inactive',
            'name' => 'form_display_inactive',
            'type' => 'true_false',
            'instructions' => 'Whether or not to display the form even if it is inactive.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'message' => 'Display If Inactive',
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
    ),
);