<?php

return array(
    'key' => 'group_5bce6c5b9e6ee',
    'title' => 'Counters',
    'fields' => array(
         array(
            'key' => 'field_606cacc32bfc7',
            'label' => 'Heading Layout',
            'name' => 'counters_heading_layout',
            'type' => 'button_group',
            'instructions' => 'Choose the Heading Layout.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33.33',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'top' => 'Top',
                'left' => 'Left',
            ),
            'allow_null' => 0,
            'default_value' => 'top',
            'layout' => 'horizontal',
            'return_format' => 'value',
        ),
        array(
            'key' => 'field_0590450fgvs255ygn',
            'label' => 'Heading Layout Columns',
            'name' => 'heading_layout_columns',
            'type' => 'true_false',
            'instructions' => 'Choose if heading shows in 2 columns. Only applies for top layout Option.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33.33',
                'class' => '',
                'id' => '',
            ),
            'message' => 'Show Heading as 2 columns',
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_298dhjnp0fj9dww238',
            'label' => 'Heading Alignment',
            'name' => 'heading_alignment',
            'type' => 'button_group',
            'instructions' => 'Choose how the heading is aligned. Only applies for top layout option.',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_2x3nfb40395746n',
                        'operator' => '!=',
                        'value' => 1,
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '33.33',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'left' => 'Left',
                'center' => 'Center',
            ),
            'allow_null' => 0,
            'default_value' => '',
            'layout' => 'horizontal',
            'return_format' => 'value',
        ),
        array(
            'key' => 'field_5bce6c6b4714a',
            'label' => 'Counter',
            'name' => 'counters',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => 'field_5bce6c934714c',
            'min' => '',
            'max' => '',
            'layout' => 'block',
            'button_label' => 'Add Counter',
            'sub_fields' => array(
                array(
                    'key' => 'field_12524952945',
                    'label' => 'Content',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_5bce6ca24714e',
                    'label' => 'Counter Prefix',
                    'name' => 'counter_prefix',
                    'type' => 'text',
                    'instructions' => 'Character shown before the number',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33.33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Prefix',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5bce6c774714b',
                    'label' => 'Final Number',
                    'name' => 'counter_number',
                    'type' => 'number',
                    'instructions' => 'Number to count up to',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33.33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Final Number',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5bce6cf04714f',
                    'label' => 'Counter Suffix',
                    'name' => 'counter_suffix',
                    'type' => 'text',
                    'instructions' => 'Character shown after the number',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33.33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Suffix',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_003mx434nbis2',
                    'label' => 'Icon',
                    'name' => 'counter_icon',
                    'type' => 'text',
                    'instructions' => 'Icon above the Title',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '<icon>',
                    'prepend' => 'fa-',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5bce6c934714c',
                    'label' => 'Title',
                    'name' => 'counter_title',
                    'type' => 'text',
                    'instructions' => 'Main title below the number',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Title',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_3948c5nu02xrn',
                    'label' => 'Options',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_5x3439sdj4x48',
                    'label' => 'Starting Value',
                    'name' => 'counter_start_val',
                    'type' => 'number',
                    'instructions' => 'The number to start counting from. (Default 0).',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Starting Number',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5cdef2125033a',
                    'label' => 'Use Easing',
                    'name' => 'counter_use_easing',
                    'type' => 'true_false',
                    'instructions' => 'Ease Animation',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui' => 1,
                    'ui_on_text' => 'True',
                    'ui_off_text' => 'False',
                ),
                array(
                    'key' => 'field_5fsrcn9850xm',
                    'label' => 'Counter Duration',
                    'name' => 'counter_duration',
                    'type' => 'number',
                    'instructions' => 'How long to take to count from the starting number to the final number (in seconds).',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '2',
                    'prepend' => '',
                    'append' => 'seconds',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5cdef2415033b',
                    'label' => 'Use Grouping',
                    'name' => 'counter_use_grouping',
                    'type' => 'true_false',
                    'instructions' => 'Example: 1,000 vs 1000',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui' => 1,
                    'ui_on_text' => 'True',
                    'ui_off_text' => 'False',
                ),
                array(
                    'key' => 'field_5cdef2505033c',
                    'label' => 'Separator',
                    'name' => 'counter_separator',
                    'type' => 'text',
                    'instructions' => 'Grouping Separator (\',\')',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Separator',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5cdef2a05033d',
                    'label' => 'Decimal',
                    'name' => 'counter_decimal',
                    'type' => 'text',
                    'instructions' => 'Decimal (\'.\')',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Decimal',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5cdef2dc5033e',
                    'label' => 'Decimal Places',
                    'name' => 'counter_decimal_places',
                    'type' => 'number',
                    'instructions' => 'Number of Decimal Places',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 0,
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => 1,
                ),
            ),
        ),
    ),
    'design_tab' => array(
        array(
            'key' => 'field_606cac77d3c2a',
            'label' => 'Text Alignment',
            'name' => 'counters_text_alignment',
            'type' => 'button_group',
            'instructions' => 'Choose how the counter text is aligned.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'left' => 'Left',
                'center' => 'Center',
            ),
            'allow_null' => 0,
            'default_value' => 'center',
            'layout' => 'horizontal',
            'return_format' => 'value',
        ),
        array(
            'key' => 'field_93847n9c3487n23c9',
            'label' => 'Coutners Per View - Small',
            'name' => 'counters_cards_per_view_sm',
            'type' => 'number',
            'instructions' => 'Number of cards to show on small screens (mobile phones)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Cards Per View',
            'prepend' => '',
            'append' => 'cards(s)',
            'min' => 1,
            'max' => 6,
            'step' => 1,
        ),
        array(
            'key' => 'field_jhfd834kjhds33f',
            'label' => 'Coutners Per View - Medium',
            'name' => 'counters_cards_per_view_md',
            'type' => 'number',
            'instructions' => 'Number of cards to show on medium screens (tablet)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Cards Per View',
            'prepend' => '',
            'append' => 'cards(s)',
            'min' => 1,
            'max' => 6,
            'step' => 1,
        ),
        array(
            'key' => 'field_287t32gjhsg71d',
            'label' => 'Coutners Per View - Large',
            'name' => 'counters_cards_per_view_lg',
            'type' => 'number',
            'instructions' => 'Number of cards to show on large screens (desktop)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Cards Per View',
            'prepend' => '',
            'append' => 'cards(s)',
            'min' => 1,
            'max' => 6,
            'step' => 1,
        ),
        array(
            'key' => 'field_94jgkdkjbigo693f',
            'label' => 'Coutners Per View - XLarge',
            'name' => 'counters_cards_per_view_xl',
            'type' => 'number',
            'instructions' => 'Number of cards to show on Xlarge screens (desktop xl)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Cards Per View',
            'prepend' => '',
            'append' => 'cards(s)',
            'min' => 1,
            'max' => 6,
            'step' => 1,
        ),
    ),
);