<?php

return array(
	'key' => 'group_tabs',
	'title' => 'Tabs',
	'fields' => array(
		array(
			'key' => 'field_43948m37nv9468594',
			'label' => 'Heading Layout Columns',
			'name' => 'heading_layout_columns',
			'type' => 'true_false',
			'instructions' => 'Choose the Heading Layout.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '51',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show Heading as 2 columns',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_6928h4n3984m3x47',
			'label' => 'Heading Alignment',
			'name' => 'heading_alignment',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_43948m37nv9468594',
						'operator' => '!=',
						'value' => 1,
					),
				),
			),
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'left' => 'Left',
				'center' => 'Center',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5bcdf0732b2f9',
			'label' => 'Tabs',
			'name' => 'tabs',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Tab/Panel',
			'sub_fields' => array(
				array(
					'key' => 'field_5bcdf3b40791b',
					'label' => 'Tab',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5bd22f7a4ef01',
					'label' => 'Tab Type',
					'name' => 'tab_type',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'text' => 'Text Only',
						'icon' => 'Icon & Text',
						'image' => 'Image',
					),
					'default_value' => 'text',
					'allow_null' => 0,
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5bcdf08d2b2fb',
					'label' => 'Tab Label',
					'name' => 'tab_label',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5bd22f7a4ef01',
								'operator' => '!=',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5dkfc39802ncka',
					'label' => 'Tab Icon Style',
					'name' => 'tab_icon_style',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5bd22f7a4ef01',
								'operator' => '==',
								'value' => 'icon',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'far' => 'Regular',
						'fal' => 'Light',
						'fas' => 'Solid',
					),
					'default_value' => 'far',
					'allow_null' => 0,
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5897bng02ncka',
					'label' => 'Tab Icon Position',
					'name' => 'tab_icon_position',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5bd22f7a4ef01',
								'operator' => '==',
								'value' => 'icon',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'top' => 'Top',
						'left' => 'Left',
					),
					'default_value' => 'top',
					'allow_null' => 0,
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5bcdf0812b2fa',
					'label' => 'Tab Icon',
					'name' => 'tab_icon',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5bd22f7a4ef01',
								'operator' => '==',
								'value' => 'icon',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'fa-<icon>',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5bd22fbefacc4',
					'label' => 'Tab Image',
					'name' => 'tab_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5bd22f7a4ef01',
								'operator' => '==',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5bcdf3c40791c',
					'label' => 'Content',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5bcbobu82b2fa',
					'label' => 'Panel Title',
					'name' => 'panel_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5bcdf0db2de34',
					'label' => 'Panel Content',
					'name' => 'panel_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_5bcdf0e92de35',
					'label' => 'Panel Link',
					'name' => 'panel_link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
				array(
					'key' => 'field_5bdassdnbkjgkcc4',
					'label' => 'Panel Image',
					'name' => 'panel_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_bnjvcf644b3',
					'label' => 'Panel Image Position',
					'name' => 'panel_image_position',
					'type' => 'button_group',
					'instructions' => 'Choose the image position of the panel image',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'left' => 'Left',
						'right' => 'Right',
					),
					'allow_null' => 0,
					'default_value' => 'left',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
			),
		),
	),
	'design_tab' => array(
		array(
			'key' => 'field_cn3043n034940c',
			'label' => 'Tabs Layout',
			'name' => 'tabs_layout',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'top' => 'Top',
				'left' => 'Left',
				'right' => 'Right',
			),
			'default_value' => 'top',
			'allow_null' => 0,
			'return_format' => 'value',
		),
	),
);