<?php

return array(
	'key' => 'group_5b74333ef40a0',
	'title' => 'Cards',
	'fields' => array(
		array(
			'key' => 'field_605b5d0c845a4',
			'label' => 'Title Layout Columns',
			'name' => 'cards_title_layout_columns',
			'type' => 'true_false',
			'instructions' => 'Choose the Ttle Layout. This only applies to top positioned Titles.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show Title as 2 columns',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5b74334196d8f',
			'label' => 'Cards',
			'name' => 'cards',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5b74335696d91',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Card',
			'sub_fields' => array(
				array(
					'key' => 'field_5409m45n2ku6nsb',
					'label' => 'Sub Header',
					'name' => 'card_sub_header',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5b74335696d91',
					'label' => 'Header',
					'name' => 'card_header',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5b74335b96d92',
					'label' => 'Content',
					'name' => 'card_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_5cdc8938aa131',
					'label' => 'Card Image',
					'name' => 'card_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5cdc8980aa132',
					'label' => 'Card Link',
					'name' => 'card_link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
			),
		),
		array(
			'key' => 'field_5as934gksdjnx',
			'label' => 'Carousel',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c378d8d8133f',
						'operator' => '==',
						'value' => 'carousel',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5df0945fks46z',
			'label' => 'Show Navigation Arrows',
			'name' => 'cards_carousel_show_navigation',
			'type' => 'true_false',
			'instructions' => 'Whether to show the navigation arrows on the carousel',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25.5',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show Arrows',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_528736aehbce3',
			'label' => 'Show Pagination Dots',
			'name' => 'cards_carousel_show_pagination',
			'type' => 'true_false',
			'instructions' => 'Whether to show the pagination dots on the carousel',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25.5',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show Dots',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_605b5fb9a5d85',
			'label' => 'Swiper Controls Layout',
			'name' => 'cards_swiper_controls_layout',
			'type' => 'button_group',
			'instructions' => 'Choose the Layout of the swiper controls',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'pagination-navigation' => 'Pagination <-> Navigation',
				'navigation-pagination' => 'Navigation <-> Pagination',
			),
			'allow_null' => 0,
			'default_value' => 'pagination-navigation',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_59384kdf2xxs2',
			'label' => 'Autoplay',
			'name' => 'cards_carousel_autoplay',
			'type' => 'true_false',
			'instructions' => 'Allow the carousel to automatically change slides.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '51',
				'class' => '',
				'id' => '',
			),
			'message' => 'Autoplay',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_52983sdjhfk2f',
			'label' => 'Autoplay Delay',
			'name' => 'cards_carousel_autoplay_delay',
			'type' => 'number',
			'instructions' => 'Delay (ms) between slides auto changing.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_59384kdf2xxs2',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'default_value' => 3000,
			'placeholder' => 3000,
			'prepend' => '',
			'append' => 'milliseconds',
			'min' => '',
			'max' => '',
			'step' => 100,
		),
		array(
			'key' => 'field_5amnsg3876dlc',
			'label' => 'Loop',
			'name' => 'cards_carousel_loop',
			'type' => 'true_false',
			'instructions' => 'Allow the carousel to loop back to the beginning.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '51',
				'class' => '',
				'id' => '',
			),
			'message' => 'Loop',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_528d36dn2os92',
			'label' => 'Speed',
			'name' => 'cards_carousel_speed',
			'type' => 'number',
			'instructions' => 'Speed at which the carousel slides',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '49',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 300,
			'prepend' => '',
			'append' => 'milliseconds',
			'min' => '',
			'max' => '',
			'step' => 50,
		),
		array(
			'key' => 'field_5so3985xm2m02',
			'label' => 'Lazy Load Images',
			'name' => 'cards_carousel_lazy_load',
			'type' => 'true_false',
			'instructions' => 'Lazy Load the Cards Images',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Lazy Load',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'design_tab' => array (
		array(
			'key' => 'field_5c378d8d8133f',
			'label' => 'Cards Layout',
			'name' => 'cards_layout',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'grid' => 'Grid',
				'carousel' => 'Carousel',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'grid',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_605a1cfdc5177',
			'label' => 'Layout',
			'name' => 'cards_carousel_layout',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c378d8d8133f',
						'operator' => '==',
						'value' => 'carousel',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'title-top' => 'Title Top',
				'title-left' => 'Title Left',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5ajt640dk2l02',
			'label' => 'Cards Per View - Small',
			'name' => 'cards_cards_per_view_sm',
			'type' => 'number',
			'instructions' => 'Number of cards to show on small screens (mobile phones)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Cards Per View',
			'prepend' => '',
			'append' => 'card(s)',
			'min' => 1,
			'max' => 6,
			'step' => 0.1,
		),
		array(
			'key' => 'field_5plsnh387sn2k',
			'label' => 'Cards Per View - Medium',
			'name' => 'cards_cards_per_view_md',
			'type' => 'number',
			'instructions' => 'Number of cards to show on medium screens (tablet)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Cards Per View',
			'prepend' => '',
			'append' => 'card(s)',
			'min' => 1,
			'max' => 6,
			'step' => 0.1,
		),
		array(
			'key' => 'field_8sdkj3xm093ld',
			'label' => 'Cards Per View - Large',
			'name' => 'cards_cards_per_view_lg',
			'type' => 'number',
			'instructions' => 'Number of cards to show on large screens (desktop)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Cards Per View',
			'prepend' => '',
			'append' => 'card(s)',
			'min' => 1,
			'max' => 6,
			'step' => 0.1,
		),
		array(
			'key' => 'field_542iruyx9z29d',
			'label' => 'Cards Per View - XLarge',
			'name' => 'cards_cards_per_view_xl',
			'type' => 'number',
			'instructions' => 'Number of cards to show on Xlarge screens (desktop xl)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Cards Per View',
			'prepend' => '',
			'append' => 'card(s)',
			'min' => 1,
			'max' => 6,
			'step' => 0.1,
		),
		array(
			'key' => 'field_5mdijbi948mz2',
			'label' => 'Show Card Images',
			'name' => 'cards_show_images',
			'type' => 'true_false',
			'instructions' => 'Whether to show the Cards Image.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show Card Images',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5aasdjh34g20k',
			'label' => 'Card Image Position',
			'name' => 'cards_image_position',
			'type' => 'radio',
			'instructions' => 'Choose the position of the image on the card. Top shows the image at the top of the card. Background makes the image a background of the card. Option has no effect if Show Card Image is turned off.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5mdijbi948mz2',
						'operator' => '==',
						'value' => 1,
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'top' => 'Top',
				'cover' => 'Background',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'top',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5nsdhkh3x903v',
			'label' => 'Card Animation',
			'name' => 'cards_animation',
			'type' => 'select',
			'instructions' => 'Choose the type of animation to show the cards on load.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => \App\Gutenberg\Animations::favorites(),
			'default_value' => array(
				0 => 'default',
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
	),
);
