<?php
return array(
	'key' => 'group_6082f45e7d3fe',
	'title' => 'Map',
	'fields' => array(
		array(
			'key' => 'field_6082f4652e2d0',
			'label' => 'Map Type',
			'name' => 'map_type',
			'type' => 'button_group',
			'instructions' => 'Google maps require an API key.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'content' => 'Content',
				'embed' => 'Embed',
				'javascript' => 'JavaScript',
				'locations' => 'Locations',
				'global' => 'Global',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_6082f4972e2d1',
			'label' => 'Map',
			'name' => 'map',
			'type' => 'google_map',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6082f4652e2d0',
						'operator' => '==',
						'value' => 'embed',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '39.7722365',
			'center_lng' => '-104.9860719',
			'zoom' => '',
			'height' => '',
		),
		array(
			'key' => 'field_6082ff266a328',
			'label' => 'Map Markers',
			'name' => 'map_markers',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6082f4652e2d0',
						'operator' => '==',
						'value' => 'javascript',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_6083047c86da1',
					'label' => 'Marker Title',
					'name' => 'map_marker_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_6082ff356a329',
					'label' => 'Map Marker',
					'name' => 'map_marker',
					'type' => 'text',
					'instructions' => 'Map marker must be a valid Latitude / Longitude pair separated by a comma or space.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '39.7722365, -104.9860719',
					'prepend' => '',
					'append' => '',
					'maxlength' => 30,
				),
				array(
					'key' => 'field_6083126e14303',
					'label' => 'Marker Phone',
					'name' => 'map_marker_phone',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_6083128714304',
					'label' => 'Marker Address',
					'name' => 'map_marker_address',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
);
