<?php

return array(
	'key' => 'group_accordion',
	'title' => 'Accordion',
	'fields' => array(
		array(
			'key' => 'field_605a1cfty1234311gwe2',
			'label' => 'Heading Layout',
			'name' => 'accordion_header_layout',
			'type' => 'button_group',
			'instructions' => 'Choose where the heading displays in the layout. Above or to the left of the accordions.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'top' => 'Top',
				'left' => 'Left',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_605b1234joijf901d2',
			'label' => 'Heading Layout Columns',
			'name' => 'heading_layout_columns',
			'type' => 'true_false',
			'instructions' => 'Choose the Heading Layout. This only applies to top positioned headings.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_605a1cfty1234311gwe2',
						'operator' => '==',
						'value' => 'top',
					),
				),
			),
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show Title as 2 columns',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_605b1234jo2435dgse44323',
			'label' => 'Heading Alignment',
			'name' => 'heading_alignment',
			'type' => 'button_group',
			'instructions' => 'Choose how to align the heading area. Only applies to top positioned and non 2 column headings.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_605a1cfty1234311gwe2',
						'operator' => '==',
						'value' => 'top',
					),
					array(
						'field' => 'field_605b1234joijf901d2',
						'operator' => '!=',
						'value' => 1,
					),
				),
			),
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'left' => 'Left',
				'center' => 'Center',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5bbf864f973d5',
			'label' => 'Accordion Items',
			'name' => 'accordion_items',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Item',
			'sub_fields' => array(
				array(
					'key' => 'field_5bbf866d973d6',
					'label' => 'Title',
					'name' => 'accordion_item_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5bbf8676973d7',
					'label' => 'Content',
					'name' => 'accordion_item_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_5bbf8b7fa4982',
			'label' => 'Icons',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5bbf9ac7cc8a9',
			'label' => 'Icon Type',
			'name' => 'accordion_items_icon_type',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'far' => 'Regular',
				'fal' => 'Light',
				'fas' => 'Solid',
			),
			'default_value' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5bbf8af1a497e',
			'label' => 'Icon Opened',
			'name' => 'accordion_items_icon_opened',
			'type' => 'text',
			'instructions' => 'Enter the <a href="https://fontawesome.com">Font Awesome</a> Icon name without the fa- prefix',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'chevron-up',
			'placeholder' => '<icon>',
			'prepend' => 'fa-',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5bbf8b0fa497f',
			'label' => 'Icon Closed',
			'name' => 'accordion_items_icon_closed',
			'type' => 'text',
			'instructions' => 'Enter the <a href="https://fontawesome.com">Font Awesome</a> Icon name without the fa- prefix',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'chevron-down',
			'placeholder' => '<icon>',
			'prepend' => 'fa-',
			'append' => '',
			'maxlength' => '',
		),
	),
	'design_tab' => array(
		array(
			'key' => 'field_5bbf831374e4f',
			'label' => 'Accordion - Type',
			'name' => 'accordion_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'full' => 'Full',
				'halves' => 'Halves',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_605b1234jo23490tijfoaq912',
			'label' => 'Accordion Box Shadow',
			'name' => 'accordion_box_shadow',
			'type' => 'true_false',
			'instructions' => 'Choose if the accordion should have a box shadow and remove the bottom border.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Add Box Shadow',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	)
);
